### PR TITLE
debug mode fix

### PR DESCRIPTION
**Pull request by amazingalek**
There's a bug in EnableDebugMode, caused by an earlier cleanup i did.
To reproduce:

1. Make sure EnableDebugMode is enabled
2. Open config menu for EnableDebugMode
3. Edit a combination and leave menus
4. You get an error

### CODE REVIEW

**Comment by TAImatem** [comment]
Ah, I suppose it's because I forgot to call `Clear`

**Comment by TAImatem** [comment]
Also, I only just realized there might be a problem with me not filtering out combination from other strings (in form of extra errors).
Maybe we should add IsType method to config?

**Comment by amazingalek** [comment]
> Ah, I suppose it's because I forgot to call `Clear`

You kinda did, I removed it in a cleanup 😥

**Comment by amazingalek** [comment]
> Also, I only just realized there might be a problem with me not filtering out combination from other strings (in form of extra errors).
> Maybe we should add IsType method to config?

Maybe and maybe. We'll deal with it when/if we need to ;-)

**Pull request merged**
