### PR TITLE
new logging project

### PR DESCRIPTION
**Pull request by amazingalek**

### CODE REVIEW

**Comment by TAImatem** [comment]
Sounds like it *might* break something 🤔

**Comment by TAImatem** [comment]
or is it 1.0 thing?

**Comment by amazingalek** [comment]
@TAImatem I'm not sure how breaky this is, will test shortly.

**Comment by TAImatem** [comment]
Although it might be fine since mods normally interact with interface, so technically if you somehow keep it the same in ModHelper it might work

**Pull request merged**
