### PR TITLE
Static gameobject to object

### PR DESCRIPTION
**Pull request by amazingalek**
Did this just so VS would complain less, making reviewing easier. These warnings accounts for about 50% of all warnings ;)

### CODE REVIEW

**Comment by TAImatem** [comment]
It didn't show warnings for this to me :shrug: It did tell that "Hey, you can simplify that"

**Comment by amazingalek** [comment]
It might be ReSharper 🤷

**Comment by TAImatem** [comment]
Go ahead though, you don't need explicit approval to merge to my branch :P

**Comment by TAImatem** [comment]
Did you test it, BTW?

**Comment by amazingalek** [comment]
I won't merge to your branch, I'll change base to dev after your branch is merged. 
Just pointing to your branch because I branched from it. If I point to dev now the diff will include your PR.

**Comment by TAImatem** [comment]
yeah, might be ReSharper turning implicit warnings into explicit warnings

**Comment by TAImatem** [comment]
Speaking of warnings:
Maybe that would be a good idea to add OwmlConsole to ModButton as well?

**Comment by TAImatem** [comment]
I did use Console quite heavily in my buttons :P

**Comment by TAImatem** [comment]
Sorry for no exactly correct dev merge >.< github's diff is a bit wonky sometimes

**Comment by amazingalek** [comment]
> 
> 
> Speaking of warnings:
> Maybe that would be a good idea to add OwmlConsole to ModButton as well?

In general, we should have a better way to write to the console from anywhere...

**Pull request merged**
