### PR TITLE
Input fields can be opened with controller

### PR DESCRIPTION
**Pull request by amazingalek**
I hate it but it works...

### CODE REVIEW

**Comment by amazingalek** [comment]
This opens the text input popups with a controller, but doesn't let you close them (with a controller). Should that be implemented as well, @Raicuparta ?

**Comment by Raicuparta** [comment]
> This opens the text input popups with a controller, but doesn't let you close them (with a controller). Should that be implemented as well, @Raicuparta ?

I think this is pretty important yes... It might seem like the game froze if suddenly nothing is responding to inputs controller inputs. Especially in situations where you don't immediately think to test the keyboard, like if you're playing on a TV or in VR.

**Comment by TAImatem** [comment]
> 
> 
> This opens the text input popups with a controller, but doesn't let you close them (with a controller). Should that be implemented as well, @Raicuparta ?

Why doesn't it let you close it? Are you sure you setup popup correctly?

**Comment by amazingalek** [comment]
> 
> 
> > This opens the text input popups with a controller, but doesn't let you close them (with a controller). Should that be implemented as well, @Raicuparta ?
> 
> Why doesn't it let you close it? Are you sure you setup popup correctly?

The popup doesn't support controller by default, haven't added support for it in OWML.

**Comment by amazingalek** [comment]
Closing this, will use CommandListener instead of ControllerButton. New PR coming soon-ish.

**Pull request closed without merging**
