### PR TITLE
Improved combination input UI, OWML config menu, refactoring of menu code

### PR DESCRIPTION
**Pull request by amazingalek**
This needs a lot of testing...

### CODE REVIEW

**Comment by amazingalek** [comment]
image
👀

**Comment by amazingalek** [comment]
Todo for release:
* make a (draft?) release on GitHub for v 0.5.0, so that the build pipeline gets the correct version number. 
    * first: disable the webhook that posts releases to Discord
* make sure the correct files are copied to the ZIP in the build pipeline.
    * Check OWML.Config.json and OWML.DefaultConfig.json

**Comment by TAImatem** [comment]
part 2 is done 😋

**Comment by amazingalek** [comment]
Unable to open text input popup with controller: 
image

**Pull request merged**
