### PR TITLE
removed unused references

### PR DESCRIPTION
**Pull request by amazingalek**
ReSharper has a nice function for removing unused references.

### CODE REVIEW

**Comment by TAImatem** [comment]
That looks like a potential headache if these references turn out to be needed for something new. Maybe wait for 1.0 thing first?

**Comment by amazingalek** [comment]
I don't get it. Doesn't VS make it (too) easy to add references?
If you now use references to see what's used where, you'll be tricked. 
And why 1.0? This shouldn't break any compatibility.

**Comment by amazingalek** [comment]
@misternebula @Raicuparta wanna weigh in?

**Comment by Raicuparta** [comment]
> @misternebula @Raicuparta wanna weigh in?

don't see the point of keeping them, approved

**Pull request merged**
