### PR TITLE
Button base

### PR DESCRIPTION
**Pull request by amazingalek**
Introduced a common base class for ModButton and ModLayoutButton.
Got rid of lots of duplicated code.
~~Untested, WIP.~~
I intend to rename ModButton to TitleButton and BaseButton to ModButton, but that'll screw up diffing, so I'll do that after first round of reviews.

### CODE REVIEW

**Comment by TAImatem** [comment]
Is it based on my PR?

**Comment by TAImatem** [comment]
Because IIRC I changed LayoutButton significantly in that PR (mostly moving stuff to LayoutManager)

**Comment by TAImatem** [comment]
But I do like that idea

**Comment by amazingalek** [comment]
Nope. It shouldn't be too much of a problem, LayoutManager doesn't contain any of the stuff I moved to the base class.

**Comment by TAImatem** [comment]
Did you think about adding value-less ModButton as common ancestor?

**Comment by amazingalek** [comment]
Not sure what you mean. 
"I intend to rename ModButton to TitleButton and BaseButton to ModButton" - does that answer it, or do you mean something else?

**Comment by amazingalek** [comment]
Tested, seems OK. Ready for review.

**Comment by TAImatem** [comment]
I meant common ancestor to ModInput<T> confused them with Modbutton

**Comment by TAImatem** [comment]
advantage would be an ability to store them in single container thing

**Comment by amazingalek** [comment]
Good idea, I was considering it in the early days but had some issues, don't remember what. 
I'll likely look into it again, but that's for another PR :)

**Comment by amazingalek** [comment]
Todo: rename buttons...

**Comment by TAImatem** [comment]
It would definitely make getting ModInput by name much simpler (I suggest using Dictionary in that case)

**Comment by amazingalek** [comment]
All buttons now share the same list (Buttons) in ModMenu, and same method for adding buttons (AddButton). Not sure I like the way it became, will experiment a little.

**Comment by amazingalek** [comment]
Happy with it again, ready for review (again)

**Pull request merged**
